definitions:
  forms.PwdForm:
    properties:
      confirm_new_pwd:
        type: string
      new_pwd:
        type: string
      old_pwd:
        type: string
      username:
        type: string
    required:
    - confirm_new_pwd
    - new_pwd
    - old_pwd
    - username
    type: object
  forms.UserInfoForm:
    properties:
      email:
        type: string
      nickname:
        type: string
      signature:
        type: string
      user_img:
        type: string
      username:
        type: string
    required:
    - email
    - username
    type: object
  utils.Result:
    properties:
      code:
        description: 状态码
        example: 100
        type: integer
      data:
        description: 数据
        type: object
      msg:
        description: 提示
        example: 密码错误
        type: string
    type: object
host: localhost:8088
info:
  contact: {}
  description: recrem 开源搜索引擎 API 接口文档
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Gin Swagger
  version: "1.0"
paths:
  /api/v1/all_users:
    get:
      consumes:
      - application/json
      responses:
        "100":
          description: Continue
          schema:
            $ref: '#/definitions/utils.Result'
        "104":
          schema:
            $ref: '#/definitions/utils.Result'
      summary: 获取所有用户
      tags:
      - 用户
  /api/v1/users:
    put:
      consumes:
      - application/json
      parameters:
      - description: 用户信息表单
        in: body
        name: userForm
        required: true
        schema:
          $ref: '#/definitions/forms.UserInfoForm'
      responses:
        "100":
          description: Continue
          schema:
            $ref: '#/definitions/utils.Result'
        "104":
          schema:
            $ref: '#/definitions/utils.Result'
      summary: 更新用户信息
      tags:
      - 用户
  /api/v1/users/pwd:
    put:
      consumes:
      - application/json
      parameters:
      - description: 修改密码表单
        in: body
        name: pwdForm
        required: true
        schema:
          $ref: '#/definitions/forms.PwdForm'
      responses:
        "100":
          description: Continue
          schema:
            $ref: '#/definitions/utils.Result'
        "104":
          schema:
            $ref: '#/definitions/utils.Result'
      summary: 修改密码
      tags:
      - 用户
swagger: "2.0"
